x-base-php-config: &php
  image: ${IMAGE_PREFIX:-cvvfcm/meteoprint-}app:${APP_VERSION:-latest}
  depends_on: [ database ]
  restart: unless-stopped
  environment:
    SERVER_NAME: ${SERVER_NAME:-localhost}, php:80
    MESSENGER_TRANSPORT_DSN: doctrine://default?auto_setup=0
    APP_SECRET: ${APP_SECRET:-!ChangeMe!}
    MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
    MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
    MERCURE_URL: ${CADDY_MERCURE_URL:-http://php/.well-known/mercure}
    MERCURE_PUBLIC_URL: ${CADDY_MERCURE_PUBLIC_URL:-https://${SERVER_NAME:-localhost}:${HTTPS_PORT:-443}/.well-known/mercure}
    MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
    DATABASE_URL: '${DATABASE_URL:-postgresql://${DATABASE_USER:-meteoprint}:${DATABASE_PASSWORD:-meteoprint}@database:5432/${DATABASE_DB:-meteoprint}?serverVersion=18&charset=utf8}'
    SYMFONY_DECRYPTION_SECRET: ${SYMFONY_DECRYPTION_SECRET:-}
  build:
    context: .
    target: app
    args:
      EXTERNAL_USER_ID: ${EXTERNAL_USER_ID}

services:
  php:
    <<: *php
    ports:
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp

  consumer:
    <<: *php
    command: 'php bin/console messenger:consume async --no-debug -vv'
    healthcheck:
      test: [ 'CMD', 'php', '-v' ]
      interval: 30s
      timeout: 10s
      retries: 3

  database:
    image: postgres:18-trixie
    volumes: [ 'database-data:/var/lib/postgresql' ]
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "${POSTGRES_DB:-meteoprint}", "-U", "${POSTGRES_USER:-meteoprint}" ]
      timeout: 5s
      retries: 5
      start_period: 60s
    environment:
      - POSTGRES_DB=${DATABASE_DB:-meteoprint}
      - POSTGRES_USER=${DATABASE_USER:-meteoprint}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-meteoprint}

volumes:
  database-data: ~

networks:
  default:
    enable_ipv6: true
