<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260617080428 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Initialize project';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE forecast (id UUID NOT NULL, position JSONB NOT NULL, day DATE NOT NULL, generated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, slots JSONB NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2A9C7844462CE4F5E5A02990 ON forecast (position, day)');
        $this->addSql('CREATE TABLE spot (id UUID NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, position JSONB NOT NULL, type VARCHAR(255) NOT NULL, ffvClubId JSONB DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B9327A73989D9B62 ON spot (slug)');
        $this->addSql('CREATE UNIQUE INDEX spot_ffv_club_lookup ON spot (ffvClubId)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE forecast');
        $this->addSql('DROP TABLE spot');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
