{{- if .Values.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "meteoprint.fullname" . }}-migrate
  labels:
    {{- include "meteoprint.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        {{- include "meteoprint.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migrate
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - php
            - bin/console
            - doctrine:migrations:migrate
            - --no-interaction
            - --all-or-nothing
          envFrom:
            - configMapRef:
                name: {{ include "meteoprint.fullname" . }}-config
            - secretRef:
                name: {{ include "meteoprint.fullname" . }}-secret
          resources:
            {{- toYaml .Values.migrations.resources | nindent 12 }}
          {{- if .Values.oracleWallet.enabled }}
          volumeMounts:
            {{- include "meteoprint.walletMount" . | nindent 12 }}
          {{- end }}
      {{- if .Values.oracleWallet.enabled }}
      volumes:
        {{- include "meteoprint.walletVolume" . | nindent 8 }}
      {{- end }}
{{- end }}
