name: Destroy infrastructure

on:
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    destroy-prod:
        name: Provision PROD
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.SCW_ACCESS_KEY }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.SCW_SECRET_KEY }}
            SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
            SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
            TAILSCALE_OAUTH_CLIENT_ID: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
            TAILSCALE_OAUTH_CLIENT_SECRET: ${{ secrets.TAILSCALE_OAUTH_CLIENT_SECRET }}
            CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v6
            -   name: Install OpenTofu
                uses: opentofu/setup-opentofu@v2
            -   name: Initialize OpenTofu
                run: tofu -chdir=.infra/terraform init
            -   name: Destroy Terraform infrastructure
                run: tofu -chdir=.infra/terraform destroy -auto-approve
